language: node_js
node_js:
  - "7.5.0"
branches:
  only:
    - gh-pages
addons:
  apt:
    packages:
      sshpass
deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: gh-pages
    skip_cleanup: true
