language: node_js
node_js:
  - "7.5.0"
branches:
  only:
    - gh-pages
addons:
  apt:
    packages:
      sshpass
deploy:
  - provider: script
    script: sshpass -p$TRAVIS_SSH_PASS ssh -o StrictHostKeyChecking=no travis@ihe.cirg.washington.edu 'cd /var/www/himss/healthy-weight/ && git fetch origin && git reset --hard origin/gh-pages'
    on:
      branch: gh-pages
